version: "3"
services:
  rest:
    image: sergionava89/products:v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "50505:50505"
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet:
