
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
    - name: "80"
      port: 80 # External port
      targetPort: 80 # Internal port

# For this to work you need to run minikube tunnel and access your service on the external ip 
# Docker desktop will link this to localhost and there won't be a need for minikube tunnel