apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - env:
      - name: MONGO_PASSWORD
        valueFrom:
        # this is defined as follow kubectl create secret generic db-passwords --from-literal=db-password='hotchocolate' --from-literal=db-root-password='hotchocolate'
          secretKeyRef:
            name: db-passwords
            key: db-password
      name: my-nginx2
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "100"
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2 # Default is 1
        periodSeconds: 5 # Default is 10
        failureThreshold: 1 # Default is 3

# kubectl create -f nginx.pod.yml --save-config
# kubectl describe pod my-nginx
# kubectl apply -f nginx.pod.yml
# kubectl exec my-nginx -ir sh
# kubectl edit -f nginx.pod.yml
# kubectl delete -f nginx.pod.yml