# Exposes an ip address for the nodes on a static port.
# Allows comunication to the outside world.

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
    - port: 80
      targetPort: 80  # Internal port
      nodePort: 31000 # External port

# This will route calls to localhost:31000 to the my-nginx pods on port 80
# When using minikube the following command will give you a url to access your service. minikube service nginx-nodeport --url